import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from '../app/Ui/Sidebar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex ">
             <div className="w-full lg:w-1/6">
             <Sidebar/>
      </div>
        <div className="flex grow p-4">{children}</div>
        
        </div>
     
      </body>
    </html>
  );
}
